[tool.flake8]
ignore = E203, W503
max-line-length = 88
exclude = __pycache__,.venv,.git

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
